### PR TITLE
Modernise project structure

### PR DESCRIPTION
**Pull request by medavox**
Hello!

This is a great instrument that I used to enjoy playing around with years ago.
I was sad when it was archived by F-Droid for being too out of date, and continued to install it despite the apparent security concerns.

I've never found another isomorphic musical keyboard app on Android - at least one that's not riddled with ads and other nuisances.

This PR modernises the build files and project structure **almost without touching the actual Java code**. I'm impressed to say that the 11 year old code only needed updating in one place in order for it to compile and run (android resource IDs are no longer constants and so can't be used in `switch` cases anymore).

I know it's probably been a long time since you thought about this app, but I'm still a fan :) so I wanted to make it compilable in 2024, in the hopes someone else can restore it to the F-Droid store in the future.

This only took me a morning, so it's not the end of the world if this doesn't get merged. I don't have the time to provide continuous maintenance & support for this app myself going forward either; but I will have scratched my itch today by getting a modern build for this classic piece of software.

### CODE REVIEW

**Comment by medavox** [comment]
I've just noticed that you are not the original author, but just the first person to fork this to github :) 

Your public profile doesn't seem very Android-based these days, so if I don't hear back from you, I will just happily continue with my own fork.

Thanks for keeping this software alive!

**Comment by lrq3000** [comment]
Dear medavox,

Thank you very much for your PR! I will merge it right away!

Do you think it would be too complicated to convert it to kotlin?

I am still very much thinking about this app and I would very much like to develop it further but I don't have any spare time to do so in the foreseeable future unfortunately. If you would like to become a maintainer for this app or just add some features from time to time, I can give you an access to this repo :-) Given your love for this app, I trust you will take good care of it.

I am not the original author indeed but I worked a bit with him when I took on improving this app. This version has a  lot more features and bugfixes compared to the originaloriginal, I don't know if they all work as I originally intended though, but one main change was improvements of the sounds management so as to have more sounds thrt can play simultaneously and of higher quality (the piano soundfont was replaced with a studio quality one) and new instruments can be added as soundfont files on the sd card (this would certainly need an update because of the SAF - if you are interested in working on this app further, I can take care of fixing the SAF, i implemented it in several other apps).

**Comment by medavox** [comment]
Oh, awesome! Thanks for the rapid response, and for merging my changes!

Kotlin conversion is absolutely doable! 👍  I just didn't want to get carried away with doing too much in one go, without creating a new stable version first. I've done a lot of Java to Kotlin migrations in my career, and the codebase for this app is impressively small given its functionaltity, so it shouldn't take too long.

Yeah having enough spare time to maintain these things absolutely is the hardest part, isn't it? 😅 

I would love to be added as a maintainer, thank you!

It's such a novel and interesting concept that it would be great to get a new release out to the stores eventually. I did something similar with a scientific caluclator app a few years ago for F-Droid, but didn't find time to continue maintaining it.

And yeah, if you could migrate to SAF that would be great!

Glad to hear you've not forgotten about it 😁 hopefully between us we can find enough time to show this app the love it deserves.

**Comment by lrq3000** [comment]
Ok awesome! Welcome aboard then :-D

Then yes I'm going to implement SAF. But my code is in Kotlin, do you think you can do the kotlin migration first or should i convert to java?

I would love to publish a new release, but we need to solve these first:
1. There is a trademark on Hexiano and its logo. So we will need to change the name and logo. Several were kindly offered in issue #2 .
2. I never published an app to fdroid, I intended to do so but everytime i try to understand the documentation I get lost lol. If you can explain to me a bit the rough outline of what to do, i will happily try!

**Comment by medavox** [comment]
Whoops, sorry I didn't see your reply earlier!

I've already started the conversion to Kotlin on my branch; shouldn't take me too long to finish it. Maybe end of the weekend, maybe 7 days?

Yeah I read through the issue, great work by everyone to get a new logo! just needs the name deciding now.

WRT F-Droid: yeah it's been a while, but if I figured it out before, I'm sure I can do it again 😅

**Comment by lrq3000** [comment]
This sounds awesome @medavox, thank you very much! I'll implement SAF right away once you will have pushed the Kotlin refactoring update :-)

Great for F-Droid, also I will see to publish on Google Play to reach a wider audience.

As a side-note, a past contributor could successfully implement midi over wifi or bluetooth (I don't remember which one), so that the app could be used as a wireless controller for desktop apps such as Ableton Live. I still have the sourcecode (in Java) somewhere on my backup harddrives, but I never had the time to properly merge the changes. Would you be interested to get the source code and potentially implement it? If not no problem at all, I am just suggesting if you are interested by this feature.

**Comment by medavox** [comment]
Yes, definitely pass along the source code if you can find it! :) Even if i don't manage to merge it in, we can put it in an orphaned branch so it's not lost, and a future contributor could continue the work

**Comment by lrq3000** [comment]
Awesome! And great idea! I will add tne sourcecode as an orphaned brancn then and you will see whether you think you can use it :-)

**Pull request merged**
